runtime: nodejs16

env_variables:
  NODE_ENV: production

handlers:
  - url: /.*
    script: auto
    secure: always

automatic_scaling:
  min_instances: 1
  max_instances: 1
  target_cpu_utilization: 0.5
  max_concurrent_requests: 10

rate_limits:
  - rate: 5/s
    burst_size: 10
