steps:
  # Install dependencies
  - name: node:16.19.1-alpine3.17
    entrypoint: npm
    args: ['install']
  # Run tests
  - name: node
    entrypoint: npm
    args: ['test']
  # Run custom commands
  - name: node
    entrypoint: npm
    args: ['run', 'build']
  # Deploy to AppEngine
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      [
        '-c',
        'gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy',
      ]
timeout: '1600s'
