steps:
  # Install dependencies
  - name: node:16.19.1-alpine3.17
    entrypoint: npm
    args: ['install']
  # Build the application
  - name: node
    entrypoint: npm
    args: ['run', 'build']
  # Deploy to AppEngine
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      [
        '-c',
        'echo $'\n  JWT_SECRET: '$$JWT_SECRET >> app.yaml' \
        '&& echo $'\n  DATABASE_URL: '$$DATABASE_URL >> app.yaml' \
        '&& gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy',
      ]
    secretEnv: ['JWT_SECRET', 'DATABASE_URL']
timeout: '1600s'
availableSecrets:
  secretManager:
    - versionName: projects/vippo-project/secrets/JWT_SECRET/versions/latest
      env: 'JWT_SECRET'
    - versionName: projects/vippo-project/secrets/DATABASE_URL/versions/latest
      env: 'DATABASE_URL'
