steps:
  # Install dependencies
  - id: install-deps
    name: node:16.19.1-alpine3.17
    entrypoint: npm
    args: ['install']
  # Migrate database schema and seed
  - id: migrate-db
    name: gcr.io/cloud-builders/npm
    entrypoint: sh
    args:
      - '-c'
      - |
        wget https://storage.googleapis.com/cloudsql-proxy/v1.23.0/cloud_sql_proxy.linux.amd64 -O /workspace/cloud_sql_proxy && chmod +x /workspace/cloud_sql_proxy
        (./workspace/cloud_sql_proxy -dir=/workspace -instances=vippo-project:us-east1:vippo-db-postgresql-development & sleep 2) && npx prisma migrate deploy && npx prisma db seed
    timeout: '1200s'
    waitFor: ['install-deps']
    secretEnv: ['DATABASE_URL']
  # Build the application
  - id: build-app
    name: node
    entrypoint: npm
    args: ['run', 'build']
  # Deploy to AppEngine
  - id: deploy-app
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    secretEnv: ['JWT_SECRET', 'DATABASE_URL']
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo $'\n  JWT_SECRET: '$$JWT_SECRET >> app.yaml
        echo $'\n  DATABASE_URL: '$$DATABASE_URL >> app.yaml
        gcloud config set app/cloud_build_timeout 1600 && gcloud app deploy
timeout: '1600s'
availableSecrets:
  secretManager:
    - versionName: projects/vippo-project/secrets/JWT_SECRET/versions/latest
      env: 'JWT_SECRET'
    - versionName: projects/vippo-project/secrets/DATABASE_URL/versions/latest
      env: 'DATABASE_URL'
